### ISSUE TITLE
error in solidus 2.1.beta1 with solidus_tracker

### ISSUE THREAD

**Issue by sechix** [solidusio-contrib/solidus_trackers#2] opened 2016-12-22 22:50 UTC
I have this error running store frontend, due to solidus_tracker code. Could you help me?

wrong number of arguments (given 0, expected 1)
Extracted source (around line #4):
2
3
4
5
6
7
              
  belongs_to :store

  def self.current(store)
    if store.is_a?(Spree::Store)
      Spree::Tracker.where(active: true, store_id: store).first
    else

**Comment by AdnanTheExcellent** [comment] 2017-02-02 21:08
I get the same issue. The problem is in the _google_analytics.html.erb file, it calls `Spree::Store.current`, but the call expects a Spree::Store as an argument. This is a bug in the gem. 

in line one of google_analytics.html.erb, update it to:

`<% if tracker = Spree::Tracker.current(current_store) %>`

**Comment by sechix** [comment] 2017-03-01 16:06
I get this error now: PG::UndefinedColumn: ERROR:  column spree_trackers.store_id does not exist.
In solidus 2.1. and also updating to solidus 2.2

**Comment by AdnanTheExcellent** [comment] 2017-03-01 16:33
have you run all the latest migrations yet? In particular, this one:

https://github.com/solidusio-contrib/solidus_trackers/blob/master/db/migrate/20160920231000_add_store_to_tracker.rb

**Comment by sechix** [comment] 2017-03-01 18:05
I have run rails g solidus_trackers:install  and bundle exec rake db:migrate. But same error.

**Comment by AdnanTheExcellent** [comment] 2017-03-01 18:10
do you see that migration file in the db/migrate folder in your project? If not, you'll need to manually copy it over and update the timestamp in the file (so its the last migration). If it is there, update the timestamp anyway. Then when you run  db:migrate, it'll run it.

**Comment by sechix** [comment] 2017-03-02 16:17
thanks a lot!!!! It solved updating timestamp of this migrating file

**Comment by funwhilelost** [comment] 2017-03-10 22:29
I'm having the same problem.  Both migrations are in my folder and both completed successfully.  My tracker is associated with my store but it's still throwing the same (wrong number of arguments) error.

```
Expected string default value for '--jbuilder'; got true (boolean)
      append  vendor/assets/javascripts/spree/frontend/all.js
      append  vendor/assets/javascripts/spree/backend/all.js
      insert  vendor/assets/stylesheets/spree/frontend/all.css
      insert  vendor/assets/stylesheets/spree/backend/all.css
         run  bundle exec rake railties:install:migrations FROM=solidus_trackers from "."
Copied migration 20170310221327_create_trackers.solidus_trackers.rb from solidus_trackers
Copied migration 20170310221328_add_store_to_tracker.solidus_trackers.rb from solidus_trackers
Would you like to run the migrations now? [Y/n]
         run  bundle exec rake db:migrate from "."
== 20170310221327 CreateTrackers: migrating ===================================

-- data_source_exists?("spree_trackers")
   -> 0.1008s
-- create_table(:spree_trackers)
   -> 0.3087s
== 20170310221327 CreateTrackers: migrated (0.6124s) ==========================
 
== 20170310221328 AddStoreToTracker: migrating ================================
-- data_source_exists?("spree_trackers")
   -> 0.2030s
-- change_table(:spree_trackers, {})
   -> 0.3076s
== 20170310221328 AddStoreToTracker: migrated (1.0206s) =======================
```

From the console:
```
[3] pry(main)> Spree::Tracker.current
ArgumentError: wrong number of arguments (given 0, expected 1)
from /Users/andrew/git/northwestwindsurf-solidus/.bundle/ruby/2.3.0/gems/solidus_trackers-1.0.0/app/models/spree/tracker.rb:4:in `current'
```

**Comment by brchristian** [comment] 2017-05-21 16:00
Getting same error here.

**Comment by brchristian** [comment] 2017-05-21 16:02
@sechix @AdnanTheExcellent @funwhilelost Note that this is fixed in the `master` branch but not yet as a numbered gem release.

@mamhoff Can we get a new rubygems release that includes this fix?

**Comment by mamhoff** [comment] 2017-05-22 10:21
@swively would you look into cutting a release?

**Comment by swively** [comment] 2017-05-23 09:05
New release cut!

**Comment by sechix** [comment] 2017-05-23 09:44
Great! thank you all!

**Closed as completed** 2017-05-23 16:47 UTC
Labels: SolidusConf Hack Day
